### ISSUE TITLE
deploy pydashie with nginx + uwsgi !?

### ISSUE THREAD

**Issue by aRkadeFR** [evolvedlight/pydashie#11]
It's not a real issue about pydashie, but the setup of the project. I would like to know how you deploy the project with uwsgi and nginx.
Everything seems to be ok for the assets but not the /events.
Would you have some nginx conf and .ini to show ?

**Comment by egalano** [comment]
To get the /events to work properly without lag due to nginx buffering, you have to set up nginx to handle Server-Sent-Events (SSE). You most likely should set these options in your location block and not at a broader scope.

```
proxy_set_header Connection '';
proxy_http_version 1.1;
chunked_transfer_encoding off;
proxy_buffering off;
proxy_cache off;
```
Info taken from: http://stackoverflow.com/questions/13672743/eventsource-server-sent-events-through-nginx

**Comment by aRkadeFR** [comment]
great, thanks for the answer
